version: "3.8"
services:
#app serverの設定#
  app-server:
    container_name: app-server
    build:
      context: ./
      dockerfile: dockerfiles/app_server.dockerfile
    networks:
      my_host_network:
        aliases:
          - py-server
    expose:
      - 9876
    restart: always

  web-server:
    container_name: web-server
    build:
      context: ./
      dockerfile: dockerfiles/nginx_product.dockerfile
    networks:
      my_host_network:
        aliases:
          - nginx-server
    ports:
      - 4443:443
      - 8080:80
    depends_on:
      - app-server
    restart: always
  db:
    image: postgres
    container_name: postgresql
    expose:
      - 5432:5432
    volumes:
      - psql-data/:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

      

networks:
  my_host_network:
    name: my-nginx-network
    driver: bridge

