version: "3.8"
services:
#app serverの設定#
  app-server:
    container_name: app-server
    build:
      context: ./
      dockerfile: dockerfiles/app_server.dockerfile
    networks:
      my_host_network:
        aliases:
          - py-server
    expose:
      - 9876
#    restart: always

  web-server:
    container_name: web-server
    build:
      context: ./
      dockerfile: dockerfiles/nginx_develop.dockerfile
    networks:
      my_host_network:
        aliases:
          - nginx-server
    ports:
      - 8080:80
#    depends_on:
#      - app-server
#    restart: always
  db:
    container_name: postgresql
    build:
      context: ./
      dockerfile: dockerfiles/postgres.dockerfile
    networks:
      my_host_network:
        aliases:
          - psql-server
    expose:
      - 5432
#    volumes:
#      - postgres/var/:/var/lib/postgresql/data
#    restart: always
    environment:
      - POSTGRES_USER=POSTGRES_USERS
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD

      

networks:
  my_host_network:
    name: my-nginx-network
    driver: bridge

